(function(){
'use strict';
var ENDPOINT='https://avelor-ai-agent.avelorsolution.workers.dev/generate-demo';
var WA='97433976563';
var selected='construction';
var controller=null;

var T={
construction:{en:'Construction',ar:'مقاولات',sub:'Industrial split layout',industry:'Construction Company',style:'Industrial',p:'#132b43',a:'#e0aa39',business:'Apex Construction',services:'Building construction, Renovation, Fit-out',desc:'Reliable construction solutions for residential and commercial projects.',layout:'construction'},
realestate:{en:'Real Estate',ar:'عقارات',sub:'Luxury property portal',industry:'Real Estate Company',style:'Luxury',p:'#18342d',a:'#c9a86a',business:'Horizon Properties',services:'Property sales, Leasing, Property management',desc:'Premium property guidance across Qatar.',layout:'realestate'},
restaurant:{en:'Restaurant & Café',ar:'مطعم ومقهى',sub:'Editorial food menu',industry:'Restaurant and Cafe',style:'Modern',p:'#4b2117',a:'#efad57',business:'Saffron Table',services:'Dining, Catering, Private events',desc:'A warm contemporary dining destination.',layout:'restaurant'},
clinic:{en:'Medical Clinic',ar:'عيادة طبية',sub:'Clean appointment dashboard',industry:'Medical Clinic',style:'Minimal',p:'#0f6674',a:'#65d0c9',business:'Nova Care Clinic',services:'General consultation, Preventive care, Diagnostics',desc:'Accessible patient-focused healthcare in Doha.',layout:'clinic'},
interior:{en:'Interior Design',ar:'تصميم داخلي',sub:'Magazine portfolio',industry:'Interior Design Studio',style:'Luxury',p:'#2e2824',a:'#c8a27b',business:'Form & Space',services:'Interior design, Space planning, 3D visualization',desc:'Thoughtful interiors shaped around how people live and work.',layout:'interior'},
fitness:{en:'Fitness & Gym',ar:'نادي رياضي',sub:'High-energy poster',industry:'Fitness and Gym',style:'Modern',p:'#111111',a:'#dbff37',business:'Pulse Fitness',services:'Personal training, Group classes, Strength coaching',desc:'Training programs built for real progress.',layout:'fitness'},
cleaning:{en:'Cleaning Services',ar:'خدمات تنظيف',sub:'Friendly service bubbles',industry:'Cleaning and Maintenance Company',style:'Modern',p:'#097a90',a:'#7ee6d6',business:'FreshNest Services',services:'Home cleaning, Office cleaning, Deep cleaning',desc:'Reliable cleaning for homes and businesses.',layout:'cleaning'},
automotive:{en:'Automotive',ar:'خدمات سيارات',sub:'Dark garage showcase',industry:'Automotive Service Center',style:'Industrial',p:'#13161a',a:'#ff5c35',business:'Torque Auto Care',services:'Diagnostics, Mechanical repair, Detailing',desc:'Professional automotive care with clear service advice.',layout:'automotive'},
beauty:{en:'Beauty & Spa',ar:'تجميل وسبا',sub:'Soft editorial booking',industry:'Beauty Salon and Spa',style:'Luxury',p:'#5c3948',a:'#e5b8b0',business:'Maison Bloom',services:'Hair styling, Skin treatments, Spa rituals',desc:'A calm beauty experience designed around you.',layout:'beauty'},
consulting:{en:'Consulting',ar:'استشارات',sub:'Executive insight grid',industry:'Professional Consulting Firm',style:'Corporate',p:'#172a4b',a:'#6ba7ff',business:'Northline Advisory',services:'Business strategy, Operations, Market advisory',desc:'Practical advice for better business decisions.',layout:'consulting'},
ecommerce:{en:'E-commerce',ar:'تجارة إلكترونية',sub:'Product-first storefront',industry:'E-commerce and Retail',style:'Modern',p:'#29204f',a:'#ffcd4d',business:'Nexa Market',services:'Curated products, Fast delivery, Customer support',desc:'A modern online store built for easy shopping.',layout:'ecommerce'},
education:{en:'Education',ar:'تعليم وأكاديمية',sub:'Course catalogue layout',industry:'Education and Academy',style:'Modern',p:'#153e75',a:'#ffb84d',business:'BrightPath Academy',services:'Professional courses, Workshops, Online learning',desc:'Practical learning for students and professionals.',layout:'education'},
law:{en:'Law Firm',ar:'مكتب محاماة',sub:'Serif authority layout',industry:'Law Firm',style:'Corporate',p:'#18222d',a:'#b99a58',business:'Al Noor Legal',services:'Corporate law, Contracts, Dispute support',desc:'Clear legal guidance with discretion and professionalism.',layout:'law'},
hotel:{en:'Hotel',ar:'فندق وضيافة',sub:'Immersive booking experience',industry:'Hotel and Hospitality',style:'Luxury',p:'#17342f',a:'#d4b775',business:'The Cedar Doha',services:'Rooms and suites, Dining, Events',desc:'A refined hospitality experience in the heart of Doha.',layout:'hotel'},
travel:{en:'Travel & Tourism',ar:'سفر وسياحة',sub:'Destination card explorer',industry:'Travel and Tourism',style:'Modern',p:'#075985',a:'#f7b84b',business:'Wander Qatar',services:'Holiday packages, Tours, Travel planning',desc:'Curated journeys built around your interests.',layout:'travel'},
tech:{en:'Technology',ar:'شركة تقنية',sub:'SaaS product dashboard',industry:'Technology Company',style:'Minimal',p:'#17123b',a:'#7c6cff',business:'Orbital Systems',services:'Software development, Cloud solutions, Automation',desc:'Technology products that simplify complex work.',layout:'tech'},
events:{en:'Events & Weddings',ar:'فعاليات وأعراس',sub:'Romantic timeline layout',industry:'Events and Weddings',style:'Luxury',p:'#4d3149',a:'#e6c0a8',business:'Luma Events',services:'Wedding planning, Corporate events, Event styling',desc:'Memorable occasions planned with care and detail.',layout:'events'},
photography:{en:'Photography',ar:'استوديو تصوير',sub:'Masonry visual portfolio',industry:'Photography Studio',style:'Minimal',p:'#121212',a:'#f0f0f0',business:'Frame Studio',services:'Commercial photography, Portraits, Events',desc:'Distinctive photography with a clear visual point of view.',layout:'photography'},
architecture:{en:'Architecture',ar:'استوديو معماري',sub:'Blueprint minimalism',industry:'Architecture Studio',style:'Minimal',p:'#26343f',a:'#d76242',business:'Axis Architecture',services:'Architectural design, Planning, Visualization',desc:'Architecture shaped by context, function and clarity.',layout:'architecture'},
logistics:{en:'Logistics',ar:'خدمات لوجستية',sub:'Route and tracking layout',industry:'Logistics and Freight',style:'Corporate',p:'#0b3558',a:'#34c38f',business:'GulfRoute Logistics',services:'Freight forwarding, Warehousing, Last-mile delivery',desc:'Reliable movement of goods across Qatar and beyond.',layout:'logistics'},
petcare:{en:'Pet Care',ar:'رعاية الحيوانات',sub:'Playful friendly layout',industry:'Pet Care and Veterinary',style:'Modern',p:'#3f5f4c',a:'#ffb86b',business:'Happy Paws Clinic',services:'Veterinary care, Grooming, Wellness checks',desc:'Friendly, professional care for pets and their families.',layout:'petcare'}
};
var order=Object.keys(T);
var ui={en:{heroTitle:'Create a Demo Website for Your Business',heroText:'Choose from 21 genuinely different website layouts, add your details, and generate a personalised concept.',templateLabel:'Choose a Website Template',templateHelp:'Every option uses a different page composition, not only a different colour.',businessName:'Business Name',location:'Location',services:'Main Services',servicesHelp:'Separate services with commas.',style:'Website Style',language:'Content Language',primaryColor:'Primary Colour',accentColor:'Accent Colour',description:'Short Business Description',phone:'Phone / WhatsApp',email:'Business Email',generate:'Create My Demo Website',generating:'Generating your website concept…',previewTitle:'Live Website Preview',desktop:'Desktop',mobile:'Mobile',regenerate:'Regenerate Concept',requestWebsite:'Request This Website',success:'Your website concept is ready.',fallback:'AI is unavailable, so a local sample concept is displayed.',requiredName:'Please enter the business name.',requiredServices:'Please enter at least one service.'},ar:{heroTitle:'أنشئ موقعاً تجريبياً لنشاطك',heroText:'اختر من 21 تخطيطاً مختلفاً فعلياً، وأدخل بياناتك، وأنشئ تصوراً مخصصاً.',templateLabel:'اختر قالب الموقع',templateHelp:'كل خيار يستخدم تركيبة صفحات مختلفة، وليس مجرد لون مختلف.',businessName:'اسم الشركة',location:'الموقع',services:'الخدمات الرئيسية',servicesHelp:'افصل بين الخدمات بفواصل.',style:'أسلوب الموقع',language:'لغة المحتوى',primaryColor:'اللون الرئيسي',accentColor:'اللون المميز',description:'وصف مختصر للنشاط',phone:'الهاتف / واتساب',email:'البريد الإلكتروني',generate:'إنشاء موقعي التجريبي',generating:'جارٍ إنشاء تصور موقعك…',previewTitle:'معاينة الموقع',desktop:'سطح المكتب',mobile:'الجوال',regenerate:'إعادة إنشاء التصور',requestWebsite:'اطلب هذا الموقع',success:'تم إنشاء تصور موقعك.',fallback:'خدمة الذكاء الاصطناعي غير متاحة، لذلك تم عرض نموذج محلي.',requiredName:'يرجى إدخال اسم الشركة.',requiredServices:'يرجى إدخال خدمة واحدة على الأقل.'}};

var form=document.getElementById('demo-generator-form'), grid=document.getElementById('demo-template-grid'), preview=document.getElementById('website-preview'), status=document.getElementById('demo-status'), stage=document.getElementById('demo-device-stage');
function esc(s){return String(s==null?'':s).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
function initials(n){return n.split(/\s+/).filter(Boolean).slice(0,2).map(function(x){return x[0]}).join('').toUpperCase()||'AI';}
function lang(){return document.documentElement.lang==='ar'?'ar':'en';}
function serviceList(v){var a=String(v||'').split(/[,،\n]+/).map(function(x){return x.trim()}).filter(Boolean); while(a.length<3)a.push(['Consultation','Professional support','Tailored service'][a.length]); return a.slice(0,3);}
function fallback(data){var ar=data.language==='Arabic';var s=serviceList(data.services);return {businessName:data.businessName,kicker:ar?'خدمات احترافية في '+data.location:'Professional services in '+data.location,heroTitle:ar?'حلول مصممة لنشاطك':'A Better Way to Move Your Business Forward',heroDescription:data.description||T[data.template].desc,aboutTitle:ar?'نبذة عن '+data.businessName:'About '+data.businessName,aboutText:data.description||T[data.template].desc,servicesTitle:ar?'خدماتنا':'What We Do',services:s.map(function(x){return {title:x,description:ar?'خدمة احترافية مصممة لتلبية احتياجات العملاء.':'A professional service shaped around customer needs.'}}),ctaTitle:ar?'لنبدأ مشروعك القادم':'Ready to Take the Next Step?',ctaText:ar?'تواصل معنا لمناقشة احتياجاتك.':'Contact our team to discuss your requirements.'};}
function data(){var t=T[selected];return {template:selected,businessName:document.getElementById('business-name').value.trim(),industry:t.industry,location:document.getElementById('location').value.trim(),services:document.getElementById('services').value.trim(),style:document.getElementById('style').value,colors:document.getElementById('primary-color').value+' and '+document.getElementById('accent-color').value,language:document.getElementById('language').value,description:document.getElementById('description').value.trim(),phone:document.getElementById('phone').value.trim(),email:document.getElementById('email').value.trim(),primary:document.getElementById('primary-color').value,accent:document.getElementById('accent-color').value};}
function cards(){grid.innerHTML='';order.forEach(function(k){var t=T[k],l=document.createElement('label');l.className='demo-template-card demo-card-'+k+(k===selected?' is-selected':'');l.innerHTML='<input type="radio" name="template" value="'+k+'" '+(k===selected?'checked':'')+'><span class="template-mini mini-'+k+'"><i></i><b></b><em></em></span><span class="demo-template-copy"><strong>'+esc(lang()==='ar'?t.ar:t.en)+'</strong><small>'+esc(t.sub)+'</small></span>';grid.appendChild(l);});}
function nav(c){return '<nav><span>Home</span><span>Services</span><span>About</span><span>Contact</span></nav>';}
function serviceCards(c,cls){return '<div class="'+cls+'">'+c.services.map(function(s,i){return '<article><span>0'+(i+1)+'</span><h4>'+esc(s.title)+'</h4><p>'+esc(s.description)+'</p></article>';}).join('')+'</div>';}
function render(c,d){var b=esc(c.businessName), mark=esc(initials(c.businessName)), hero=esc(c.heroTitle), desc=esc(c.heroDescription), kick=esc(c.kicker), about=esc(c.aboutText), cta=esc(c.ctaTitle), ct=esc(c.ctaText);var s=serviceCards(c,'site-services');var html='';
switch(selected){
case 'construction': html='<header class="c-head"><b>'+mark+'</b><strong>'+b+'</strong>'+nav()+'<button>Get a Quote</button></header><section class="c-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Start a Project</button></div><aside><span>BUILD</span><i></i></aside></section><section class="c-band"><b>Planning</b><b>Building</b><b>Delivery</b></section>'+s+'<section class="site-cta"><h2>'+cta+'</h2><p>'+ct+'</p></section>';break;
case 'realestate': html='<header class="re-head"><strong>'+b+'</strong>'+nav()+'<button>List Property</button></header><section class="re-hero"><div class="re-copy"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><div class="re-search"><span>Location</span><span>Property Type</span><button>Search</button></div></div><div class="re-photo"><span>Featured Property</span><b>West Bay Residence</b></div></section><section class="re-listings"><h2>Curated Properties</h2><div><article>Waterfront Apartment</article><article>Family Villa</article><article>Commercial Office</article></div></section>'+s;break;
case 'restaurant': html='<header class="rs-head"><strong>'+b+'</strong><span>MENU</span><span>STORY</span><button>Reserve</button></header><section class="rs-hero"><div class="rs-title"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p></div><div class="rs-plate"><i></i><b>Chef’s Selection</b></div></section><section class="rs-menu"><h2>Today’s Menu</h2><div><article><b>01</b><h4>'+esc(c.services[0].title)+'</h4></article><article><b>02</b><h4>'+esc(c.services[1].title)+'</h4></article><article><b>03</b><h4>'+esc(c.services[2].title)+'</h4></article></div></section><section class="rs-story"><blockquote>“Food creates the best kind of memory.”</blockquote><p>'+about+'</p></section>';break;
case 'clinic': html='<header class="cl-head"><strong>'+b+'</strong><div><span>Our Doctors</span><span>Services</span><button>Book Appointment</button></div></header><section class="cl-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Book a Visit</button></div><div class="cl-card"><b>Next Available</b><strong>Today · 4:30 PM</strong><span>General Consultation</span></div></section><section class="cl-stats"><span><b>Same-day</b>appointments</span><span><b>Patient-first</b>care</span><span><b>Modern</b>facilities</span></section>'+s;break;
case 'interior': html='<header class="in-head"><strong>'+b+'</strong><span>Selected Projects</span><span>Studio</span></header><section class="in-hero"><div class="in-image"></div><div class="in-copy"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><a>Explore the studio →</a></div></section><section class="in-mag"><span>01</span><h2>'+esc(c.aboutTitle)+'</h2><p>'+about+'</p></section><section class="in-projects"><article>Residence / Doha</article><article>Hospitality / Lusail</article><article>Workspace / West Bay</article></section>';break;
case 'fitness': html='<header class="ft-head"><strong>'+b+'</strong><button>JOIN NOW</button></header><section class="ft-hero"><div class="ft-word">MOVE</div><div class="ft-copy"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Start Training</button></div><div class="ft-stripe"></div></section><section class="ft-programs">'+c.services.map(function(x,i){return '<article><b>0'+(i+1)+'</b><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p></article>';}).join('')+'</section>';break;
case 'cleaning': html='<header class="cn-head"><strong>'+b+'</strong><button>Book Cleaning</button></header><section class="cn-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Get Instant Estimate</button></div><div class="cn-bubbles"><i></i><i></i><i></i><b>Fresh spaces<br>feel better</b></div></section><section class="cn-steps"><article>1<span>Choose a service</span></article><article>2<span>Pick a time</span></article><article>3<span>Enjoy the result</span></article></section>'+s;break;
case 'automotive': html='<header class="au-head"><strong>'+b+'</strong><span>Services</span><span>Workshop</span><button>Book Service</button></header><section class="au-hero"><div class="au-speed">PERFORMANCE</div><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Schedule Inspection</button></div></section><section class="au-dash"><span><b>01</b>Diagnostics</span><span><b>02</b>Repair</span><span><b>03</b>Care</span></section>'+s;break;
case 'beauty': html='<header class="bt-head"><strong>'+b+'</strong><span>Services</span><span>Journal</span><button>Book</button></header><section class="bt-hero"><div class="bt-portrait"></div><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><a>Discover our rituals</a></div></section><section class="bt-services">'+c.services.map(function(x){return '<article><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p><span>Explore →</span></article>';}).join('')+'</section>';break;
case 'consulting': html='<header class="co-head"><strong>'+b+'</strong>'+nav()+'<button>Start a Conversation</button></header><section class="co-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p></div><aside><b>01</b><span>Strategy</span><b>02</b><span>Execution</span><b>03</b><span>Growth</span></aside></section><section class="co-insight"><h2>Insight that turns into action.</h2><p>'+about+'</p></section>'+s;break;
case 'ecommerce': html='<header class="ec-head"><strong>'+b+'</strong><div class="ec-search">Search products</div><span>Bag (0)</span></header><section class="ec-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Shop New Arrivals</button></div><div class="ec-product"><i></i><b>Featured Collection</b><span>QAR 249</span></div></section><section class="ec-grid"><article>New arrivals</article><article>Best sellers</article><article>Limited edition</article><article>Everyday essentials</article></section>';break;
case 'education': html='<header class="ed-head"><strong>'+b+'</strong><span>Courses</span><span>Instructors</span><button>Enrol</button></header><section class="ed-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Browse Courses</button></div><div class="ed-progress"><b>Learning Path</b><i style="--w:72%"></i><span>72% practical learning</span></div></section><section class="ed-courses">'+c.services.map(function(x,i){return '<article><span>Course 0'+(i+1)+'</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p><button>View course</button></article>';}).join('')+'</section>';break;
case 'law': html='<header class="lw-head"><strong>'+b+'</strong><span>Practice Areas</span><span>Our Firm</span><button>Consultation</button></header><section class="lw-hero"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><div><button>Request Consultation</button><span>Discretion · Clarity · Counsel</span></div></section><section class="lw-rule"></section><section class="lw-practice">'+c.services.map(function(x,i){return '<article><b>0'+(i+1)+'</b><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p></article>';}).join('')+'</section>';break;
case 'hotel': html='<section class="ht-hero"><header><strong>'+b+'</strong><span>Stay</span><span>Dine</span><span>Experience</span><button>Book Now</button></header><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p></div><form><span>Check in</span><span>Check out</span><span>Guests</span><button>Check availability</button></form></section><section class="ht-experience"><h2>Stay beautifully.</h2><p>'+about+'</p><div><article>Rooms & Suites</article><article>Dining</article><article>Events</article></div></section>';break;
case 'travel': html='<header class="tr-head"><strong>'+b+'</strong><span>Destinations</span><span>Trips</span><button>Plan My Journey</button></header><section class="tr-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p></div><div class="tr-ticket"><b>DOH</b><i></i><b>WORLD</b><span>Your next journey starts here</span></div></section><section class="tr-cards"><article>Desert Escape</article><article>City Weekend</article><article>Island Retreat</article></section>';break;
case 'tech': html='<header class="tc-head"><strong>'+b+'</strong><span>Product</span><span>Solutions</span><button>Get Demo</button></header><section class="tc-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Start Building</button></div><div class="tc-ui"><div class="tc-side"></div><div class="tc-chart"><i></i><i></i><i></i><i></i></div><span>Live operations</span></div></section><section class="tc-logos">SECURE <b>·</b> FAST <b>·</b> SCALABLE</section>'+s;break;
case 'events': html='<header class="ev-head"><strong>'+b+'</strong><span>Weddings</span><span>Events</span><button>Plan With Us</button></header><section class="ev-hero"><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><div class="ev-date"><b>12</b><span>DEC<br>2026</span></div></section><section class="ev-story"><span>01</span><h2>From first idea to final moment.</h2><p>'+about+'</p></section><section class="ev-grid"><article>Ceremony</article><article>Celebration</article><article>Details</article></section>';break;
case 'photography': html='<header class="ph-head"><strong>'+b+'</strong><span>Work</span><span>About</span><span>Contact</span></header><section class="ph-intro"><h1>'+hero+'</h1><p>'+desc+'</p></section><section class="ph-masonry"><article><span>01</span></article><article><span>02</span></article><article><span>03</span></article><article><span>04</span></article><article><span>05</span></article></section><section class="ph-foot"><p>'+about+'</p><a>View full portfolio →</a></section>';break;
case 'architecture': html='<header class="ar-head"><strong>'+b+'</strong><span>Projects</span><span>Practice</span><span>Contact</span></header><section class="ar-hero"><div class="ar-lines"></div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><b>01 / 04</b></section><section class="ar-project"><div></div><aside><span>Selected Project</span><h2>House on the Edge</h2><p>'+about+'</p></aside></section>'+s;break;
case 'logistics': html='<header class="lg-head"><strong>'+b+'</strong><span>Solutions</span><span>Tracking</span><button>Track Shipment</button></header><section class="lg-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><div class="lg-track"><span>Enter tracking number</span><button>Track</button></div></div><div class="lg-map"><i></i><i></i><i></i><svg viewBox="0 0 100 60"><path d="M5,45 C25,5 45,55 95,12"/></svg></div></section><section class="lg-metrics"><span><b>24/7</b>visibility</span><span><b>3 modes</b>road · sea · air</span><span><b>1 partner</b>end to end</span></section>'+s;break;
case 'petcare': html='<header class="pc-head"><strong>'+b+'</strong><span>Services</span><span>Our Team</span><button>Book Visit</button></header><section class="pc-hero"><div><small>'+kick+'</small><h1>'+hero+'</h1><p>'+desc+'</p><button>Book a Check-up</button></div><div class="pc-pet"><span>♥</span><b>Happy pets,<br>happy homes.</b></div></section><section class="pc-pills">'+c.services.map(function(x){return '<article><i>●</i><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p></article>';}).join('')+'</section>';break;
}
preview.className='generated-site template-'+selected;preview.style.setProperty('--primary',d.primary);preview.style.setProperty('--accent',d.accent);preview.innerHTML='<div class="concept-watermark">AI CONCEPT</div>'+html;document.querySelector('.demo-browser-address').textContent=(c.businessName||'yourcompany').toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,28)+'.qa';}
function defaults(k){selected=k;var t=T[k];document.getElementById('industry').value=t.industry;document.getElementById('business-name').value=t.business;document.getElementById('services').value=t.services;document.getElementById('description').value=t.desc;document.getElementById('style').value=t.style;document.getElementById('primary-color').value=t.p;document.getElementById('accent-color').value=t.a;document.getElementById('primary-color-value').textContent=t.p.toUpperCase();document.getElementById('accent-color-value').textContent=t.a.toUpperCase();cards();var d=data();render(fallback(d),d);}
function translate(){var L=ui[lang()];document.querySelectorAll('[data-demo-i18n]').forEach(function(e){var k=e.getAttribute('data-demo-i18n');if(L[k])e.textContent=L[k];});cards();}
grid.addEventListener('change',function(e){if(e.target.name==='template')defaults(e.target.value);});
document.querySelectorAll('.lang-option').forEach(function(b){b.addEventListener('click',function(){document.documentElement.lang=b.dataset.lang;document.documentElement.dir=b.dataset.lang==='ar'?'rtl':'ltr';document.querySelectorAll('.lang-option').forEach(function(x){x.classList.toggle('is-active',x===b)});translate();});});
document.querySelectorAll('[data-preview-size]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[data-preview-size]').forEach(function(x){x.classList.remove('is-active')});b.classList.add('is-active');stage.classList.toggle('is-mobile',b.dataset.previewSize==='mobile');});});
['primary-color','accent-color'].forEach(function(id){document.getElementById(id).addEventListener('input',function(){document.getElementById(id+'-value').textContent=this.value.toUpperCase();var d=data();render(fallback(d),d);});});
form.addEventListener('submit',async function(e){e.preventDefault();var d=data();if(!d.businessName){status.textContent=ui[lang()].requiredName;return}if(!d.services){status.textContent=ui[lang()].requiredServices;return}status.textContent=ui[lang()].generating;document.getElementById('generate-demo-btn').classList.add('is-loading');if(controller)controller.abort();controller=new AbortController();try{var r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d),signal:controller.signal});if(!r.ok)throw new Error('HTTP '+r.status);var j=await r.json();if(!j.success||!j.content)throw new Error('Invalid');render(j.content,d);status.textContent=ui[lang()].success;}catch(err){render(fallback(d),d);status.textContent=ui[lang()].fallback;}finally{document.getElementById('generate-demo-btn').classList.remove('is-loading');}});
document.getElementById('regenerate-btn').addEventListener('click',function(){form.requestSubmit();});
document.getElementById('request-website-btn').addEventListener('click',function(e){e.preventDefault();var d=data();var m='Hello AVELOR, I created a demo website concept.\nBusiness: '+d.businessName+'\nIndustry: '+d.industry+'\nTemplate: '+T[selected].en;window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(m),'_blank','noopener');});
cards();defaults('construction');translate();
})();
